### PR TITLE
Proposal: Inject adapters, punt to adapter where appropriate.

### PR DESCRIPTION
**Pull request by paragonie-scott**
See #4, #5

### CODE REVIEW

**Comment by paragonie-scott** [comment]
I added a `stringToStream()` method to `AdapterInterface`  that turns a `string` into a `StreamInterface` based on whatever adapter is being used.

I moved Guzzle to a dev dependency, and that should probably be done with all adapters we include.

**Comment by mcordingley** [comment]
Don't forget to [suggest](https://getcomposer.org/doc/04-schema.md#suggest) packages.

**Comment by paragonie-scott** [comment]
If the tests pass in Travis CI as they do locally, I'll merge this and then work on adding other adapters. (e.g. symfony/http-foundation, Slim, you name it really)

**Comment by mcordingley** [comment]
Ack, we're back to depending on some sort of HTTP client for access to the functions. This is going to make it hard to build server code using them.

**Comment by paragonie-scott** [comment]
> Edit: I may be misunderstanding the full scope of the adapters, so I'll sit back and be quiet for a moment.

Yes, you will absolutely need some sort of HTTP client and/or server implementation. But we don't care which one.

**Comment by paragonie-scott** [comment]
The workaround here is, we could provide our own HTTP `Request`, `Response`, and `Stream` objects and create a generic adapter for it.

**Comment by mcordingley** [comment]
I just looked around and yes, PSR-7 applies there too. At least a few of the main frameworks don't appear to really use them right now which will be a problem with integrating this into their request/response flows. They _should_ migrate to use them over time, but it's an open question how long that'll take.

**Comment by paragonie-scott** [comment]
I'll make the `GenericAdapter` idea a separate Github issue.

**Comment by mcordingley** [comment]
The specific case that I'm staring down is the idea of making middleware in Laravel to sign responses and verify requests. That middleware would be given a Laravel request object and return a Laravel response object (though these are Symfony-derived). I don't think the adapters are going to fly here. Without having looked too closely at the other frameworks, I would expect similar issues.

**Comment by paragonie-scott** [comment]
> I don't think the adapters are going to fly here.

Yeah, they don't seem to implement PSR-7 yet. 

For Laravel/Symfony middleware, you'll probably need to create a wrapper class that implements the PSR-7 interface and encapsulates the native Request/Response objects.

**Comment by mcordingley** [comment]
I'm kicking around the idea of writing up a package that implements this for Laravel, since I really do need this.

**Comment by paragonie-scott** [comment]
I'm going to release v0.3 in a bit if you want to use that as a minimum version.

When I find time to write the generic adapter, I'll release v0.4.0 which makes Sapient's constructor argument optional (will default to the generic adapter). I might eschew creating any other framework-specific adapters in our library itself, in favor of handing framework-specific users the interface and documentation for creating their own adapter.

I think that will be the most scalable approach, since I don't know how many dozens of ways PSR-7 will be implemented in various projects.

**Pull request merged**
